### ISSUE TITLE
Onomy artifact does not work

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/heighliner#68]
```
 go run ./main.go build --chain onomy --registry ghcr.io/strangelove-ventures/heighliner --version v1.0.0
```

Result:

```
❯ docker run --entrypoint sh -it ghcr.io/strangelove-ventures/heighliner/onomy:v1.0.0
~ $ onomyd
sh: onomyd: not found
~ $ exit
```

As a workaround, I'm going to create and push my own docker image.

**Comment by DavidNix** [comment]
The example above does not show the whole picture. `ls -l /bin/onomy` returns the binary. So it's there. It's not missing.

**Comment by agouin** [comment]
Updating this issue with external conversation. `ldd /bin/onomyd` shows that `onomyd` is not a static binary. It depends on shared libraries that do not exist in the final heighliner image. In order to build it as a static binary as heighliner expects, onomy needs to consume the LDFLAGS environment variable in the Makefile https://github.com/strangelove-ventures/onomy/commit/7df2a99def641d88627896a8a9a8d0e51ef665d1

**Comment by DavidNix** [comment]
I wasn't able to get plain `make install` working with our fork. Still the same issue. In https://github.com/strangelove-ventures/heighliner/pull/81 I have a workaround where we specify the build-target in its entirety. I'm leaving this issue open so we can address later. I've spent almost the whole day trying to get onomy images working and need to move on.

**Comment by DavidNix** [comment]
Fyi, we need https://github.com/onomyprotocol/onomy/pull/129 merged from the Onomy team before heighliner build server starts working correctly.
